### ISSUE TITLE
Add Forgotten Items

### ISSUE THREAD

**Issue by JaselUmena** [HeartlessAUS/Crisps-of-the-Multiverse#1]
Can we add this mod? It really encourages exploration, as the recipes included in it can only be discovered in dungeons and the like, and none of the items it adds other than the golem armor is too powerful. Among other stuff, you can get:

- Basic tools that stay with you on death.

- Talismans (with durability) that allow you to smelt, summon water, use fall damage to attack or teleport within a certain range.

- Armor that's overall better than dragon scale armor (except for the chestplate) and negates knockback (alternative endgame gear).

- Miscellaneous tools like a vein miner pick, a pickaxe that uses ores to attack with explosions (the better the ore, the more powerful the explosion), a pick that mines as fast as gold but with more durability, spring boots, a thing to float on water without sinking and a small et-cetera.

Pros: Trinkets and decent equipment to encourage not staying in the same place building a base forever. The trinkets aren't really overpowered either, as their functionality can already be performed with other items the pack already contains.

**Comment by HeartlessAUS** [comment]
Added in V2.2
