### ISSUE TITLE
Monster modifier  problem: Sticky.

### ISSUE THREAD

**Issue by JaselUmena** [HeartlessAUS/Crisps-of-the-Multiverse#12]
I've been noticing an issue recently with a modifier monsters can randomly have. The sticky modifier makes the item you hold in your main hand drop to the floor when the monster that has it takes damage. The following does not matter:

- If you are not actively attacking the monster.
- If it dies to an AOE effect.

This causes items you are holding to randomly drop even if you have left the area where the monster is, just because it happened to step on an AOE you casted ages ago and you forgot about already. Problems it has:

- It does not make any sound to notify you lost your item, so you may not even notice that's the case.
- Items on this server lay flat on the floor, which makes them harder to see, impossible if it's on soul sand or similar blocks where the player can sink.
- Leaves on this server are fall through, making any item that falls on them be under it thus making it hard to see.
- If the mob also has stormy (summons lightning upon taking damage), it will instantly delete the item you dropped without any way to get it back.

Counterplay: If you see a mob with sticky, punch it, don't use a valuable item. This does not work with aoes or the mob taking random damage.

Big issue: Items that gain experience or level up such as magic wands take literal hours to replace.

Solution: Check on the config and disable the sticky modifier. The world will be a better place without it because there is no way to prevent it in some cases.

**Comment by HeartlessAUS** [comment]
Fixed in BETA V2.2
  - Sticky modifier disabled
  - Storm modifier disabled

Both were done for particular reasons
