### ISSUE TITLE
Issue: The betweenlands Primordial Malevolence crash.

### ISSUE THREAD

**Issue by JaselUmena** [HeartlessAUS/Crisps-of-the-Multiverse#15]
After completing his dungeon and triggering his spawn, the primordial malevolence boss seems to cause a crash to anybody in render distance. Some kind of GUI problem according to the crash log. Perhaps there is a way to disable the special hud in the config?

**Comment by HeartlessAUS** [comment]
update in future to either lock mo'creatures in overworld, or remove it

**Comment by HeartlessAUS** [comment]
Mo'creatures removed in V2.3 due to the incompatibility and no sane way to correct the issue
