### ISSUE TITLE
Mod suggestion: Grimoire of gaia

### ISSUE THREAD

**Issue by JaselUmena** [HeartlessAUS/Crisps-of-the-Multiverse#3]
This is a fun mod that adds that I used to like back in 1.7.10 which adds a big variety of mobs with brand new models. The mobs themselves are actually quite strong, but they don't do anything crazy, so it's a given that this mod will be mostly safe to use on the server.

[https://www.curseforge.com/minecraft/mc-mods/grimoire-of-gaia](url)

**Comment by HeartlessAUS** [comment]
Added in V2.2
