### ISSUE TITLE
Mod suggestion: EnderIO

### ISSUE THREAD

**Issue by JaselUmena** [HeartlessAUS/Crisps-of-the-Multiverse#4]
Since there is thermal expansion and ender storage, this is a mod that I have always loved. It includes machinery and all, but the most important and useful part is its cables. They are like any other mod's cables but you can have multiple on the same block, and they are really useful for redstone constructions. It also has refined storage integration.

[https://www.curseforge.com/minecraft/mc-mods/ender-io](url)

**Comment by HeartlessAUS** [comment]
Added in V2.2
