### ISSUE TITLE
Performance issue: Blood moon

### ISSUE THREAD

**Issue by JaselUmena** [HeartlessAUS/Crisps-of-the-Multiverse#5]
Whenever a blood moon rises, the server performance slows down quite a lot. This not only makes the night slower, but the excessive spawnrate of enemies makes it so that your FPS drop as well. It is possible to skip a blood moon using the time control spell (makes the sun set or rise, 1 day cooldown), but this should be looked at.

**Comment by HeartlessAUS** [comment]
Spawn Multiplier dumbed down to 2, instead of 4. this should make it alot less laggy

Possible fix for BETA V2
